<?PHP
$sql = <<<DATA
SELECT MARKA,
       SUM(CASE WHEN MONTH(FATTAR) = 1 THEN DLR_FonGeliri ELSE 0 END) 'Ocak',
       SUM(CASE WHEN MONTH(FATTAR) = 2 THEN DLR_FonGeliri ELSE 0 END) 'Subat',
       SUM(CASE WHEN MONTH(FATTAR) = 3 THEN DLR_FonGeliri ELSE 0 END) 'Mart',
       SUM(CASE WHEN MONTH(FATTAR) = 4 THEN DLR_FonGeliri ELSE 0 END) 'Nisan',
       SUM(CASE WHEN MONTH(FATTAR) = 5 THEN DLR_FonGeliri ELSE 0 END) 'Mayis',
       SUM(CASE WHEN MONTH(FATTAR) = 6 THEN DLR_FonGeliri ELSE 0 END) 'Haziran',
       SUM(CASE WHEN MONTH(FATTAR) = 7 THEN DLR_FonGeliri ELSE 0 END) 'Temmuz',
       SUM(CASE WHEN MONTH(FATTAR) = 8 THEN DLR_FonGeliri ELSE 0 END) 'Agustos',
       SUM(CASE WHEN MONTH(FATTAR) = 9 THEN DLR_FonGeliri ELSE 0 END) 'Eylul',
       SUM(CASE WHEN MONTH(FATTAR) = 10 THEN DLR_FonGeliri ELSE 0 END) 'Ekim',
       SUM(CASE WHEN MONTH(FATTAR) = 11 THEN DLR_FonGeliri ELSE 0 END) 'Kasim',
       SUM(CASE WHEN MONTH(FATTAR) = 12 THEN DLR_FonGeliri ELSE 0 END) 'Aralik',
       SUM(DLR_FonGeliri) 'TOPLAM'
FROM aaaa_erp_kt_komisyon_raporu
WHERE YEAR(FATTAR)=2025
GROUP BY MARKA
UNION ALL
SELECT 'TOPLAM' AS MARKA,
       SUM(CASE WHEN MONTH(FATTAR) = 1 THEN DLR_FonGeliri ELSE 0 END) 'Ocak',
       SUM(CASE WHEN MONTH(FATTAR) = 2 THEN DLR_FonGeliri ELSE 0 END) 'Subat',
       SUM(CASE WHEN MONTH(FATTAR) = 3 THEN DLR_FonGeliri ELSE 0 END) 'Mart',
       SUM(CASE WHEN MONTH(FATTAR) = 4 THEN DLR_FonGeliri ELSE 0 END) 'Nisan',
       SUM(CASE WHEN MONTH(FATTAR) = 5 THEN DLR_FonGeliri ELSE 0 END) 'Mayis',
       SUM(CASE WHEN MONTH(FATTAR) = 6 THEN DLR_FonGeliri ELSE 0 END) 'Haziran',
       SUM(CASE WHEN MONTH(FATTAR) = 7 THEN DLR_FonGeliri ELSE 0 END) 'Temmuz',
       SUM(CASE WHEN MONTH(FATTAR) = 8 THEN DLR_FonGeliri ELSE 0 END) 'Agustos',
       SUM(CASE WHEN MONTH(FATTAR) = 9 THEN DLR_FonGeliri ELSE 0 END) 'Eylul',
       SUM(CASE WHEN MONTH(FATTAR) = 10 THEN DLR_FonGeliri ELSE 0 END) 'Ekim',
       SUM(CASE WHEN MONTH(FATTAR) = 11 THEN DLR_FonGeliri ELSE 0 END) 'Kasim',
       SUM(CASE WHEN MONTH(FATTAR) = 12 THEN DLR_FonGeliri ELSE 0 END) 'Aralik',
       SUM(DLR_FonGeliri) 'TOPLAM'
FROM aaaa_erp_kt_komisyon_raporu
WHERE YEAR(FATTAR)=2025
DATA;

?>